# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantblog', '0002_auto_20190713_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_user_id',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
