# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantblog', '0003_auto_20190713_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='number',
        ),
    ]
